# docker-compose.yml corregido
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rutadirecta-app
    container_name: rd-gdl-app
    restart: unless-stopped
    working_dir: /var/www
    # Quitamos el puerto 3306 de aquí, la app ya tiene el 8005 (o el que uses)
    ports:
      - "8005:8000"
    volumes:
      - ./:/var/www
    networks:
      - rd-network

  db:
    image: mysql:8.0
    container_name: rd-gdl-db
    restart: unless-stopped
    # PONEMOS el puerto 3306 aquí para que DBeaver pueda entrar
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rutadirecta_db
      MYSQL_ROOT_PASSWORD: secret_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - rd-network

  phpmyadmin:
    image: phpmyadmin
    container_name: rd-gdl-pma
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    networks:
      - rd-network

networks:
  rd-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
